### ISSUE TITLE
Problème de syntaxe pour la fonctionnalité 4 : rechercher une salle par un créneau et une capacité

### ISSUE THREAD

**Issue by Xtazhoxton** [CocoChart/GL02_A24_NoFoundTeam_fork#7]
Quand on lance simplement la recherche en utilisant l'exemple donnée par exemple on obtient :  une erreur de syntaxe while(capacité <0) à la ligne 631. On veut donc réparer cet erreur pour que la fonctionnalité marche.

**Comment by CocoChart** [comment]
Le bug a déjà une issue
